"""gastos 2b: compartidos deudas seguimientos reglas presupuestos importaciones

Revision ID: 0c231bb99cf0
Revises: 42422874d19e
Create Date: 2026-10-01 18:27:36.347389
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0c231bb99cf0"
down_revision: str | None = "42422874d19e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_import_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_profiles")),
        sa.UniqueConstraint("user_id", "name", name=op.f("uq_import_profiles_user_id")),
    )
    op.create_index(
        op.f("ix_import_profiles_user_id"), "import_profiles", ["user_id"], unique=False
    )
    op.create_table(
        "people",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_people_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
        sa.UniqueConstraint("user_id", "name", name=op.f("uq_people_user_id")),
    )
    op.create_index(op.f("ix_people_user_id"), "people", ["user_id"], unique=False)
    op.create_table(
        "trackers",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("opening_date", sa.Date(), nullable=False),
        sa.Column("category_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.String(length=80)), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_trackers_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trackers")),
        sa.UniqueConstraint("user_id", "name", name=op.f("uq_trackers_user_id")),
    )
    op.create_index(op.f("ix_trackers_user_id"), "trackers", ["user_id"], unique=False)
    op.create_table(
        "budgets",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_budgets_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_budgets_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
        sa.UniqueConstraint("user_id", "category_id", name=op.f("uq_budgets_user_id")),
    )
    op.create_index(op.f("ix_budgets_user_id"), "budgets", ["user_id"], unique=False)
    op.create_table(
        "category_rules",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("pattern", sa.String(length=160), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('learned', 'manual')", name=op.f("ck_category_rules_source_valid")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_category_rules_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_category_rules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category_rules")),
        sa.UniqueConstraint("user_id", "pattern", name=op.f("uq_category_rules_user_id")),
    )
    op.create_index(op.f("ix_category_rules_user_id"), "category_rules", ["user_id"], unique=False)
    op.create_table(
        "debts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("opening_date", sa.Date(), nullable=False),
        sa.Column("interest_rate", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('debo', 'me_deben')", name=op.f("ck_debts_direction_valid")
        ),
        sa.CheckConstraint("status IN ('viva', 'saldada')", name=op.f("ck_debts_status_valid")),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_debts_person_id_people"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_debts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_debts")),
    )
    op.create_index(op.f("ix_debts_user_id"), "debts", ["user_id"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('committed', 'undone')", name=op.f("ck_import_batches_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_import_batches_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_import_batches_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(op.f("ix_import_batches_user_id"), "import_batches", ["user_id"], unique=False)
    op.create_table(
        "movement_shares",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("movement_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("settled_by_movement_id", sa.UUID(), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('me_deben', 'debo')", name=op.f("ck_movement_shares_direction_valid")
        ),
        sa.CheckConstraint(
            "status IN ('pendiente', 'saldada')", name=op.f("ck_movement_shares_status_valid")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_movement_shares_amount_positive")),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["movements.id"],
            name=op.f("fk_movement_shares_movement_id_movements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_movement_shares_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["settled_by_movement_id"],
            ["movements.id"],
            name=op.f("fk_movement_shares_settled_by_movement_id_movements"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_movement_shares_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movement_shares")),
    )
    op.create_index(
        op.f("ix_movement_shares_movement_id"), "movement_shares", ["movement_id"], unique=False
    )
    op.create_index(
        op.f("ix_movement_shares_person_id"), "movement_shares", ["person_id"], unique=False
    )
    op.create_index(
        op.f("ix_movement_shares_user_id"), "movement_shares", ["user_id"], unique=False
    )
    op.add_column("movements", sa.Column("debt_id", sa.UUID(), nullable=True))
    op.add_column("movements", sa.Column("import_batch_id", sa.UUID(), nullable=True))
    op.add_column("movements", sa.Column("bank_ref", sa.String(length=80), nullable=True))
    op.add_column(
        "movements",
        sa.Column("matched_planned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.drop_constraint(op.f("uq_movements_user_id"), "movements", type_="unique")
    op.create_unique_constraint(
        op.f("uq_movements_user_id"), "movements", ["user_id", "account_id", "bank_ref"]
    )
    op.create_index(op.f("ix_movements_debt_id"), "movements", ["debt_id"], unique=False)
    op.create_index(
        op.f("ix_movements_import_batch_id"), "movements", ["import_batch_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_movements_debt_id_debts"),
        "movements",
        "debts",
        ["debt_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_movements_debt_id_debts"), "movements", type_="foreignkey")
    op.drop_index(op.f("ix_movements_import_batch_id"), table_name="movements")
    op.drop_index(op.f("ix_movements_debt_id"), table_name="movements")
    op.drop_constraint(op.f("uq_movements_user_id"), "movements", type_="unique")
    op.create_unique_constraint(
        op.f("uq_movements_user_id"),
        "movements",
        ["user_id", "external_ref"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("movements", "matched_planned")
    op.drop_column("movements", "bank_ref")
    op.drop_column("movements", "import_batch_id")
    op.drop_column("movements", "debt_id")
    op.drop_index(op.f("ix_movement_shares_user_id"), table_name="movement_shares")
    op.drop_index(op.f("ix_movement_shares_person_id"), table_name="movement_shares")
    op.drop_index(op.f("ix_movement_shares_movement_id"), table_name="movement_shares")
    op.drop_table("movement_shares")
    op.drop_index(op.f("ix_import_batches_user_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_debts_user_id"), table_name="debts")
    op.drop_table("debts")
    op.drop_index(op.f("ix_category_rules_user_id"), table_name="category_rules")
    op.drop_table("category_rules")
    op.drop_index(op.f("ix_budgets_user_id"), table_name="budgets")
    op.drop_table("budgets")
    op.drop_index(op.f("ix_trackers_user_id"), table_name="trackers")
    op.drop_table("trackers")
    op.drop_index(op.f("ix_people_user_id"), table_name="people")
    op.drop_table("people")
    op.drop_index(op.f("ix_import_profiles_user_id"), table_name="import_profiles")
    op.drop_table("import_profiles")
    # ### end Alembic commands ###
