"""objetivos y parametros fiscales 2025-2026

Revision ID: 1eb9bc3e1c5d
Revises: 7a3d9e2b4c51
Create Date: 2026-10-02 13:08:54.721631
"""

from collections.abc import Sequence
from datetime import UTC, date, datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

from app.ids import uuid7

revision: str = "1eb9bc3e1c5d"
down_revision: str | None = "7a3d9e2b4c51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goals",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("target_value", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('edad_fi', 'fondo_emergencia', 'patrimonio', 'cartera_en_fecha', 'fijos_max', 'tasa_ahorro_min')",
            name=op.f("ck_goals_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_goals_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goals")),
    )
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    # --- Parámetros fiscales verificados en fuente oficial el 2026-10-02 -------------------
    # 2026 = lo vigente a esa fecha (si la Ley de Presupuestos de Canarias de 2027 vuelve a
    # deflactar con efectos del año anterior, hay que revisarlo).
    aeat = "https://sede.agenciatributaria.gob.es/Sede/ayuda/manuales-videos-folletos/manuales-practicos/"
    irpf_est = (
        aeat
        + "irpf-2025/c15-calculo-impuesto-determinacion-cuotas-integras/gravamen-base-liquidable-general/gravamen-estatal.html"
    )
    irpf_cn = (
        aeat
        + "irpf-2025/c15-calculo-impuesto-determinacion-cuotas-integras/gravamen-base-liquidable-general/gravamen-autonomico/comunidad-autonoma-canarias.html"
    )
    min_est = (
        aeat
        + "irpf-2025/c14-adecuacion-impuesto-circunstancias-personales/minimo-personal-familiar.html"
    )
    min_cn = (
        aeat
        + "irpf-2025/c14-adecuacion-impuesto-circunstancias-personales/minimo-autonomico-personal-familiar/comunidad-autonoma-canarias-minimo-ppf.html"
    )
    ip_est = (
        aeat
        + "patrimonio-2025/c-4-determinacion-base-liquidable-integra/determinacion-cuota-integra/regla-general/escala-estatal.html"
    )
    ley_ip = "https://www.boe.es/buscar/act.php?id=BOE-A-1991-14392"
    ley_irpf = "https://www.boe.es/buscar/act.php?id=BOE-A-2006-20764"

    def t(*pairs):
        return {"tramos": [{"hasta": h, "tipo": r} for h, r in pairs]}

    rows = [
        (
            "ES",
            "general_escala",
            t(
                ("12450", "0.095"),
                ("20200", "0.12"),
                ("35200", "0.15"),
                ("60000", "0.185"),
                ("300000", "0.225"),
                (None, "0.245"),
            ),
            irpf_est,
            "Escala estatal de la base liquidable general (art. 63 LIRPF).",
        ),
        (
            "ES-CN",
            "general_escala",
            t(
                ("13748", "0.09"),
                ("19422", "0.115"),
                ("35924", "0.14"),
                ("57566", "0.185"),
                ("93268", "0.235"),
                ("123745", "0.25"),
                (None, "0.26"),
            ),
            irpf_cn,
            "Escala autonómica de Canarias (art. 18 bis DL 1/2009, deflactada por la "
            "Ley 9/2025 de Presupuestos de Canarias para 2026, BOC 29-12-2025).",
        ),
        (
            "ES",
            "minimo_contribuyente",
            {"general": "5550", "mayor_65": "1150", "mayor_75": "1400"},
            min_est,
            "Mínimo del contribuyente estatal (art. 57 LIRPF).",
        ),
        (
            "ES-CN",
            "minimo_contribuyente",
            {"general": "5606", "mayor_65": "1162", "mayor_75": "1414"},
            min_cn,
            "Mínimo del contribuyente para el gravamen autonómico de Canarias.",
        ),
        (
            "ES",
            "patrimonio_escala",
            t(
                ("167129.45", "0.002"),
                ("334252.88", "0.003"),
                ("668499.75", "0.005"),
                ("1336999.51", "0.009"),
                ("2673999.01", "0.013"),
                ("5347998.03", "0.017"),
                ("10695996.06", "0.021"),
                (None, "0.035"),
            ),
            ip_est,
            "Escala estatal del IP (art. 30 Ley 19/1991). Canarias no tiene escala propia.",
        ),
        (
            "ES-CN",
            "patrimonio_minimo_exento",
            {"importe": "700000"},
            ley_ip,
            "Mínimo exento en Canarias (art. 29 DL 1/2009 de Canarias; coincide con el estatal).",
        ),
        (
            "ES",
            "patrimonio_vivienda_exenta",
            {"importe": "300000"},
            ley_ip,
            "Vivienda habitual exenta hasta 300.000 € (art. 4.Nueve Ley 19/1991).",
        ),
        (
            "ES",
            "patrimonio_limite_conjunto",
            {"limite": "0.60", "reduccion_max": "0.80"},
            ley_ip,
            "Límite conjunto IRPF + IP: 60 % de la base imponible del IRPF; la cuota de IP no se "
            "reduce más del 80 % (art. 31 Ley 19/1991).",
        ),
        (
            "ES",
            "ahorro_escala",
            t(
                ("6000", "0.19"),
                ("50000", "0.21"),
                ("200000", "0.23"),
                ("300000", "0.27"),
                (None, "0.30"),
            ),
            ley_irpf,
            "Base liquidable del ahorro, estatal + autonómica (arts. 66 y 76 LIRPF).",
        ),
    ]
    params = sa.table(
        "tax_parameters",
        sa.column("id", sa.Uuid),
        sa.column("year", sa.Integer),
        sa.column("region", sa.String),
        sa.column("key", sa.String),
        sa.column("value", JSONB),
        sa.column("source_url", sa.Text),
        sa.column("reviewed_at", sa.Date),
        sa.column("notes", sa.Text),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    now = datetime.now(UTC)
    data = []
    for year in (2025, 2026):
        for region, key, value, url, notes in rows:
            if year == 2026 and key == "ahorro_escala":
                continue  # ya sembrada en c6e72d8db597
            data.append(
                {
                    "id": uuid7(),
                    "year": year,
                    "region": region,
                    "key": key,
                    "value": value,
                    "source_url": url,
                    "reviewed_at": date(2026, 10, 2),
                    "notes": notes,
                    "created_at": now,
                    "updated_at": now,
                }
            )
    op.bulk_insert(params, data)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_table("goals")
    op.execute(
        "DELETE FROM tax_parameters WHERE reviewed_at = '2026-10-02' AND NOT (year = 2026 AND key = 'ahorro_escala')"
    )
    # ### end Alembic commands ###
