"""gastos: cuentas ciclos movimientos recurrentes fraccionadas

Revision ID: 42422874d19e
Revises: 1c39c2d0ce7d
Create Date: 2026-10-01 16:29:57.166665
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "42422874d19e"
down_revision: str | None = "1c39c2d0ce7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("bank", sa.String(length=80), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("opening_date", sa.Date(), nullable=False),
        sa.Column("apy", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('gastos', 'refugio', 'inversion', 'efectivo', 'otra')",
            name=op.f("ck_accounts_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_accounts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.create_table(
        "categories",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=False),
        sa.Column("color", sa.String(length=9), nullable=False),
        sa.Column("fixed", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('gasto', 'ingreso', 'transferencia')", name=op.f("ck_categories_kind_valid")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_categories_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("user_id", "parent_id", "name", name=op.f("uq_categories_user_id")),
    )
    op.create_index(op.f("ix_categories_user_id"), "categories", ["user_id"], unique=False)
    op.create_table(
        "installment_plans",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=160), nullable=False),
        sa.Column("merchant", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=12), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("every_months", sa.Integer(), nullable=False),
        sa.Column("first_due", sa.Date(), nullable=False),
        sa.Column("fee", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("external_ref", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('paypal', 'klarna', 'tarjeta', 'amazon', 'eci', 'otro')",
            name=op.f("ck_installment_plans_provider_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('activa', 'liquidada', 'cancelada')",
            name=op.f("ck_installment_plans_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_installment_plans_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_installment_plans_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_installment_plans_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_installment_plans")),
        sa.UniqueConstraint("user_id", "external_ref", name=op.f("uq_installment_plans_user_id")),
    )
    op.create_index(
        op.f("ix_installment_plans_user_id"), "installment_plans", ["user_id"], unique=False
    )
    op.create_table(
        "pay_cycles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("payroll_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("carried_real", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("carried_expected", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("discrepancy", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("payroll_movement_id", sa.UUID(), nullable=True),
        sa.Column("external_ref", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('open', 'closed')", name=op.f("ck_pay_cycles_status_valid")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_pay_cycles_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_pay_cycles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pay_cycles")),
        sa.UniqueConstraint("user_id", "account_id", "label", name=op.f("uq_pay_cycles_user_id")),
    )
    op.create_index(op.f("ix_pay_cycles_user_id"), "pay_cycles", ["user_id"], unique=False)
    op.create_index(
        "uq_pay_cycles_one_open",
        "pay_cycles",
        ["user_id", "account_id"],
        unique=True,
        postgresql_where="status = 'open'",
    )
    op.create_table(
        "recurring_templates",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("concept", sa.String(length=160), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("amount_is_estimate", sa.Boolean(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("every_months", sa.Integer(), nullable=False),
        sa.Column("day_of_month", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("review", sa.String(length=10), nullable=False),
        sa.Column("est_saving_year", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('gasto', 'ingreso', 'nomina', 'transferencia', 'reembolso', 'ajuste')",
            name=op.f("ck_recurring_templates_kind_valid"),
        ),
        sa.CheckConstraint(
            "review IN ('ok', 'revisar', 'cancelar')",
            name=op.f("ck_recurring_templates_review_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_recurring_templates_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_recurring_templates_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_recurring_templates_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurring_templates")),
    )
    op.create_index(
        op.f("ix_recurring_templates_user_id"), "recurring_templates", ["user_id"], unique=False
    )
    op.create_table(
        "movements",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("concept", sa.String(length=160), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("expression", sa.Text(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("transfer_pair_id", sa.UUID(), nullable=True),
        sa.Column("refund_of_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_ref", sa.UUID(), nullable=True),
        sa.Column("external_ref", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('gasto', 'ingreso', 'nomina', 'transferencia', 'reembolso', 'ajuste')",
            name=op.f("ck_movements_kind_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'recurring', 'installment', 'savings_plan', 'excel', 'bank_import')",
            name=op.f("ck_movements_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('planned', 'posted', 'cancelled')", name=op.f("ck_movements_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_movements_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_movements_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["pay_cycles.id"],
            name=op.f("fk_movements_cycle_id_pay_cycles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["refund_of_id"],
            ["movements.id"],
            name=op.f("fk_movements_refund_of_id_movements"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_movements_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movements")),
        sa.UniqueConstraint("user_id", "external_ref", name=op.f("uq_movements_user_id")),
    )
    op.create_index("ix_movements_user_concept", "movements", ["user_id", "concept"], unique=False)
    op.create_index("ix_movements_user_cycle", "movements", ["user_id", "cycle_id"], unique=False)
    op.create_index(op.f("ix_movements_user_id"), "movements", ["user_id"], unique=False)
    op.create_table(
        "recurring_price_changes",
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("old_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("new_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["recurring_templates.id"],
            name=op.f("fk_recurring_price_changes_template_id_recurring_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurring_price_changes")),
    )
    op.create_index(
        op.f("ix_recurring_price_changes_template_id"),
        "recurring_price_changes",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "installments",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("movement_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pendiente', 'pagada', 'adelantada', 'cancelada')",
            name=op.f("ck_installments_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["movements.id"],
            name=op.f("fk_installments_movement_id_movements"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["installment_plans.id"],
            name=op.f("fk_installments_plan_id_installment_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_installments")),
        sa.UniqueConstraint("plan_id", "seq", name=op.f("uq_installments_plan_id")),
    )
    op.create_table(
        "movement_lines",
        sa.Column("movement_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("note", sa.String(length=160), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["movements.id"],
            name=op.f("fk_movement_lines_movement_id_movements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movement_lines")),
    )
    op.create_index(
        op.f("ix_movement_lines_movement_id"), "movement_lines", ["movement_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movement_lines_movement_id"), table_name="movement_lines")
    op.drop_table("movement_lines")
    op.drop_table("installments")
    op.drop_index(
        op.f("ix_recurring_price_changes_template_id"), table_name="recurring_price_changes"
    )
    op.drop_table("recurring_price_changes")
    op.drop_index(op.f("ix_movements_user_id"), table_name="movements")
    op.drop_index("ix_movements_user_cycle", table_name="movements")
    op.drop_index("ix_movements_user_concept", table_name="movements")
    op.drop_table("movements")
    op.drop_index(op.f("ix_recurring_templates_user_id"), table_name="recurring_templates")
    op.drop_table("recurring_templates")
    op.drop_index(
        "uq_pay_cycles_one_open", table_name="pay_cycles", postgresql_where="status = 'open'"
    )
    op.drop_index(op.f("ix_pay_cycles_user_id"), table_name="pay_cycles")
    op.drop_table("pay_cycles")
    op.drop_index(op.f("ix_installment_plans_user_id"), table_name="installment_plans")
    op.drop_table("installment_plans")
    op.drop_index(op.f("ix_categories_user_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
