"""revision trimestral

Revision ID: 8adc8994ee04
Revises: 1eb9bc3e1c5d
Create Date: 2026-10-02 17:47:52.581732
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8adc8994ee04"
down_revision: str | None = "1eb9bc3e1c5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quarterly_reviews",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("quarter", sa.String(length=7), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("changed", sa.Text(), nullable=False),
        sa.Column("next_steps", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_quarterly_reviews_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quarterly_reviews")),
        sa.UniqueConstraint("user_id", "quarter", name="uq_quarterly_reviews_quarter"),
    )
    op.create_index(
        op.f("ix_quarterly_reviews_user_id"), "quarterly_reviews", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quarterly_reviews_user_id"), table_name="quarterly_reviews")
    op.drop_table("quarterly_reviews")
    # ### end Alembic commands ###
