"""exposicion y parametros fiscales

Revision ID: c6e72d8db597
Revises: 5f1c2a9d7e10
Create Date: 2026-10-02 12:16:15.190089
"""

from collections.abc import Sequence
from datetime import UTC, date, datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB

from app.ids import uuid7

revision: str = "c6e72d8db597"
down_revision: str | None = "5f1c2a9d7e10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tax_parameters",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("region", sa.String(length=8), nullable=False),
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("reviewed_at", sa.Date(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tax_parameters_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_parameters")),
        sa.UniqueConstraint("year", "region", "key", "user_id", name="uq_tax_param"),
    )
    op.create_table(
        "asset_exposures",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("dimension", sa.String(length=8), nullable=False),
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("weight", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("source", sa.String(length=6), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "dimension IN ('sector', 'region', 'pais', 'divisa')",
            name=op.f("ck_asset_exposures_dimension_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('auto', 'manual')", name=op.f("ck_asset_exposures_source_valid")
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_exposures_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_asset_exposures_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_exposures")),
        sa.UniqueConstraint("asset_id", "dimension", "key", name="uq_exposure_asset_dim_key"),
    )
    op.create_index(
        op.f("ix_asset_exposures_user_id"), "asset_exposures", ["user_id"], unique=False
    )
    # Escala de la base del ahorro (estatal + autonómica, igual en todas las CCAA): 2026
    params = sa.table(
        "tax_parameters", sa.column("id", sa.Uuid), sa.column("year", sa.Integer),
        sa.column("region", sa.String), sa.column("key", sa.String), sa.column("value", JSONB),
        sa.column("source_url", sa.Text), sa.column("reviewed_at", sa.Date),
        sa.column("notes", sa.Text), sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )  # fmt: skip
    now = datetime.now(UTC)
    op.bulk_insert(params, [{
        "id": uuid7(), "year": 2026, "region": "ES", "key": "ahorro_escala",
        "value": {"tramos": [
            {"hasta": "6000", "tipo": "0.19"}, {"hasta": "50000", "tipo": "0.21"},
            {"hasta": "200000", "tipo": "0.23"}, {"hasta": "300000", "tipo": "0.27"},
            {"hasta": None, "tipo": "0.30"},
        ]},
        "source_url": "https://www.boe.es/buscar/act.php?id=BOE-A-2006-20764",
        "reviewed_at": date(2026, 10, 2),
        "notes": "Ley 35/2006 del IRPF, arts. 66 y 76 (redacción tras la Ley 7/2024): suma de "
                 "los gravámenes estatal y autonómico de la base liquidable del ahorro.",
        "created_at": now, "updated_at": now,
    }])  # fmt: skip
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_asset_exposures_user_id"), table_name="asset_exposures")
    op.drop_table("asset_exposures")
    op.drop_table("tax_parameters")
    # ### end Alembic commands ###
