"""inversiones 3a

Revision ID: d2cad526f303
Revises: 0c231bb99cf0
Create Date: 2026-10-01 19:46:36.067282
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d2cad526f303"
down_revision: str | None = "0c231bb99cf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_classes",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("default_tolerance_pp", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_asset_classes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_classes")),
        sa.UniqueConstraint("user_id", "name", name="uq_asset_classes_user_name"),
    )
    op.create_index(op.f("ix_asset_classes_user_id"), "asset_classes", ["user_id"], unique=False)
    op.create_table(
        "portfolio_snapshots",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value_eur", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cost_eur", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("net_flow_eur", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("manual", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_portfolio_snapshots_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_snapshots")),
        sa.UniqueConstraint("user_id", "date", name="uq_portfolio_snapshot_day"),
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_user_id"), "portfolio_snapshots", ["user_id"], unique=False
    )
    op.create_table(
        "platforms",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("units_decimals", sa.Integer(), nullable=False),
        sa.Column("default_fee", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('broker', 'exchange', 'banco', 'otro')", name=op.f("ck_platforms_kind_valid")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_platforms_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_platforms_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platforms")),
        sa.UniqueConstraint("user_id", "name", name="uq_platforms_user_name"),
    )
    op.create_index(op.f("ix_platforms_user_id"), "platforms", ["user_id"], unique=False)
    op.create_table(
        "assets",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("asset_class_id", sa.UUID(), nullable=True),
        sa.Column("platform_id", sa.UUID(), nullable=True),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("ticker", sa.String(length=20), nullable=True),
        sa.Column("coingecko_id", sa.String(length=60), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price_provider", sa.String(length=10), nullable=False),
        sa.Column("price_ref", sa.String(length=120), nullable=True),
        sa.Column("units_decimals", sa.Integer(), nullable=True),
        sa.Column("sector", sa.String(length=60), nullable=True),
        sa.Column("country", sa.String(length=60), nullable=True),
        sa.Column("watchlist", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price_provider IN ('ft', 'coingecko', 'manual')",
            name=op.f("ck_assets_price_provider_valid"),
        ),
        sa.CheckConstraint(
            "type IN ('fondo', 'etf', 'accion', 'cripto', 'cuenta', 'otro')",
            name=op.f("ck_assets_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_class_id"],
            ["asset_classes.id"],
            name=op.f("fk_assets_asset_class_id_asset_classes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
            name=op.f("fk_assets_platform_id_platforms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_assets_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
    )
    op.create_index(op.f("ix_assets_user_id"), "assets", ["user_id"], unique=False)
    op.create_index("ix_assets_user_isin", "assets", ["user_id", "isin"], unique=False)
    op.create_table(
        "allocation_targets",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.String(length=6), nullable=False),
        sa.Column("asset_class_id", sa.UUID(), nullable=True),
        sa.Column("asset_id", sa.UUID(), nullable=True),
        sa.Column("target_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("min_pct", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("max_pct", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("tolerance_pp", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('macro', 'asset')", name=op.f("ck_allocation_targets_level_valid")
        ),
        sa.ForeignKeyConstraint(
            ["asset_class_id"],
            ["asset_classes.id"],
            name=op.f("fk_allocation_targets_asset_class_id_asset_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_allocation_targets_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_allocation_targets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocation_targets")),
    )
    op.create_index(
        op.f("ix_allocation_targets_user_id"), "allocation_targets", ["user_id"], unique=False
    )
    op.create_index(
        "ix_targets_user_level",
        "allocation_targets",
        ["user_id", "level", "valid_from"],
        unique=False,
    )
    op.create_table(
        "asset_snapshots",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("units", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("value_eur", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cost_eur", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("net_flow_eur", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_snapshots_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_asset_snapshots_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_snapshots")),
        sa.UniqueConstraint("asset_id", "date", name="uq_snapshot_asset_date"),
    )
    op.create_index(
        op.f("ix_asset_snapshots_user_id"), "asset_snapshots", ["user_id"], unique=False
    )
    op.create_table(
        "inv_transactions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("settle_date", sa.Date(), nullable=True),
        sa.Column("amount_eur", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("units", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("avg_cost", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("fee", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("pair_id", sa.UUID(), nullable=True),
        sa.Column("movement_id", sa.UUID(), nullable=True),
        sa.Column("external_id", sa.String(length=120), nullable=True),
        sa.Column("dedupe_hash", sa.String(length=64), nullable=True),
        sa.Column("import_batch_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('posicion_inicial', 'compra', 'venta', 'aportacion_periodica', 'traspaso_salida', 'traspaso_entrada', 'dividendo', 'interes', 'comision', 'recompensa')",
            name=op.f("ck_inv_transactions_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pendiente_vl', 'liquidada', 'cancelada')",
            name=op.f("ck_inv_transactions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_inv_transactions_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_inv_transactions_import_batch_id_import_batches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["movements.id"],
            name=op.f("fk_inv_transactions_movement_id_movements"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pair_id"],
            ["inv_transactions.id"],
            name=op.f("fk_inv_transactions_pair_id_inv_transactions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_inv_transactions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inv_transactions")),
        sa.UniqueConstraint("user_id", "dedupe_hash", name="uq_inv_tx_dedupe"),
    )
    op.create_index(
        op.f("ix_inv_transactions_user_id"), "inv_transactions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_inv_tx_user_asset_date",
        "inv_transactions",
        ["user_id", "asset_id", "trade_date"],
        unique=False,
    )
    op.create_table(
        "position_corrections",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("units_before", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("units_after", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("avg_cost_before", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("avg_cost_after", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_position_corrections_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_position_corrections_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_corrections")),
    )
    op.create_index(
        op.f("ix_position_corrections_user_id"), "position_corrections", ["user_id"], unique=False
    )
    op.create_table(
        "price_history",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_price_history_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_price_history_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_history")),
        sa.UniqueConstraint("asset_id", "date", name="uq_price_asset_date"),
    )
    op.create_index(op.f("ix_price_history_user_id"), "price_history", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_history_user_id"), table_name="price_history")
    op.drop_table("price_history")
    op.drop_index(op.f("ix_position_corrections_user_id"), table_name="position_corrections")
    op.drop_table("position_corrections")
    op.drop_index("ix_inv_tx_user_asset_date", table_name="inv_transactions")
    op.drop_index(op.f("ix_inv_transactions_user_id"), table_name="inv_transactions")
    op.drop_table("inv_transactions")
    op.drop_index(op.f("ix_asset_snapshots_user_id"), table_name="asset_snapshots")
    op.drop_table("asset_snapshots")
    op.drop_index("ix_targets_user_level", table_name="allocation_targets")
    op.drop_index(op.f("ix_allocation_targets_user_id"), table_name="allocation_targets")
    op.drop_table("allocation_targets")
    op.drop_index("ix_assets_user_isin", table_name="assets")
    op.drop_index(op.f("ix_assets_user_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_platforms_user_id"), table_name="platforms")
    op.drop_table("platforms")
    op.drop_index(op.f("ix_portfolio_snapshots_user_id"), table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    op.drop_index(op.f("ix_asset_classes_user_id"), table_name="asset_classes")
    op.drop_table("asset_classes")
    # ### end Alembic commands ###
